import { existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

/**
 * The Behavior Layer (design doc 11): one canonical behavior spec, rendered
 * into per-harness formats. MCP gives an agent tools; this gives it behavior:
 * checkpoint at the right moments, announce every save, detect handoffs. The
 * "software" is prose; this module is the renderer, the installer, and the
 * consent/pause state the server's guardrails read.
 */

export const BEHAVIOR_HARNESSES = [
  "claude-code",
  "cursor",
  "opencode",
  "gemini",
  "agents-md",
  "codex",
  "openclaw",
  "hermes",
  "generic",
] as const;
export type BehaviorHarness = (typeof BEHAVIOR_HARNESSES)[number];

/** The Agent Skills SKILL.md frontmatter + body, shared by every harness that
    reads a SKILL.md (Claude Code, OpenCode, OpenClaw, Hermes). One canonical
    body, one frontmatter schema (name + description), so the same skill is
    portable across their skill systems. */
function skillFile(body: string): string {
  return `---
name: ctxfile
description: Automatic context checkpointing via the ctxfile MCP tools. Use throughout every session - at session start (load context), when tasks complete or decisions are made (checkpoint), and when the user hands work off or says goodbye.
---

${body}
`;
}

/** Managed-block markers for append-style targets (AGENTS.md, .cursorrules),
    same pattern as the git hook: reinstall updates in place, uninstall is a
    clean cut. */
export const BEHAVIOR_BLOCK_BEGIN = "<!-- ctxfile:behaviors:begin (managed; do not edit inside) -->";
export const BEHAVIOR_BLOCK_END = "<!-- ctxfile:behaviors:end -->";

/** The canonical spec ships inside the npm package beside dist/. */
export function loadCanonicalBehaviors(): string {
  const here = path.dirname(fileURLToPath(import.meta.url));
  for (const candidate of [
    path.join(here, "..", "behaviors", "canonical.md"),
    path.join(here, "..", "..", "behaviors", "canonical.md"),
  ]) {
    if (existsSync(candidate)) return readFileSync(candidate, "utf8");
  }
  throw new Error("behaviors/canonical.md not found beside the ctxfile package");
}

export interface RenderedBehavior {
  harness: BehaviorHarness;
  /** Path relative to the render root (or the suggested install location). */
  relativePath: string;
  content: string;
}

/** Deterministic renders from the single source; the repo's committed
    render/ folder is regenerated by scripts/render-behaviors.mjs and a test
    fails if it drifts from this function's output. */
export function renderBehavior(harness: BehaviorHarness, canonical = loadCanonicalBehaviors()): RenderedBehavior {
  const body = canonical.trim();
  switch (harness) {
    case "claude-code":
      return { harness, relativePath: "claude-code/SKILL.md", content: skillFile(body) };
    case "opencode":
      // OpenCode also auto-reads .claude/skills/, but its own path is explicit.
      return { harness, relativePath: "opencode/SKILL.md", content: skillFile(body) };
    case "openclaw":
      return { harness, relativePath: "openclaw/SKILL.md", content: skillFile(body) };
    case "hermes":
      return { harness, relativePath: "hermes/SKILL.md", content: skillFile(body) };
    case "gemini":
      return {
        harness,
        relativePath: "gemini/GEMINI.md",
        content: `${BEHAVIOR_BLOCK_BEGIN}
## ctxfile: automatic context checkpointing

${body}
${BEHAVIOR_BLOCK_END}
`,
      };
    case "cursor":
      return {
        harness,
        relativePath: "cursor/ctxfile.mdc",
        content: `---
description: ctxfile automatic context checkpointing (announced, never silent)
alwaysApply: true
---

${body}
`,
      };
    case "agents-md":
      return {
        harness,
        relativePath: "agents-md/SECTION.md",
        content: `${BEHAVIOR_BLOCK_BEGIN}
## ctxfile: automatic context checkpointing

${body}
${BEHAVIOR_BLOCK_END}
`,
      };
    case "codex":
      return {
        harness,
        relativePath: "codex/instructions.md",
        content: `# ctxfile behaviors for Codex\n\nAdd this to your Codex instructions (global \`~/.codex/AGENTS.md\` or per-project AGENTS.md).\n\n${body}\n`,
      };
    case "generic":
      return {
        harness,
        relativePath: "generic/system-prompt.md",
        content: `# ctxfile behaviors (generic system-prompt block)\n\nPaste into the system prompt of any harness with the ctxfile MCP connected (OpenRouter wrappers, open models, custom agents).\n\n${body}\n`,
      };
  }
}

export function renderAllBehaviors(canonical = loadCanonicalBehaviors()): RenderedBehavior[] {
  return BEHAVIOR_HARNESSES.map((h) => renderBehavior(h, canonical));
}

// ---------------------------------------------------------------------------
// Install (what `ctxfile init` does per detected harness)
// ---------------------------------------------------------------------------

export interface DetectedHarness {
  harness: BehaviorHarness;
  reason: string;
}

/** Cheap, honest detection: directories the harnesses actually create. */
export function detectHarnesses(root: string, home: string): DetectedHarness[] {
  const found: DetectedHarness[] = [];
  if (existsSync(path.join(root, ".claude")) || existsSync(path.join(home, ".claude"))) {
    found.push({ harness: "claude-code", reason: ".claude directory present" });
  }
  if (existsSync(path.join(root, ".cursor")) || existsSync(path.join(home, ".cursor"))) {
    found.push({ harness: "cursor", reason: ".cursor directory present" });
  }
  if (existsSync(path.join(root, ".opencode")) || existsSync(path.join(home, ".config", "opencode"))) {
    found.push({ harness: "opencode", reason: ".opencode directory present" });
  }
  if (existsSync(path.join(root, ".gemini")) || existsSync(path.join(home, ".gemini"))) {
    found.push({ harness: "gemini", reason: ".gemini directory present" });
  }
  if (existsSync(path.join(root, "AGENTS.md"))) {
    found.push({ harness: "agents-md", reason: "AGENTS.md present" });
  }
  if (existsSync(path.join(home, ".codex"))) {
    found.push({ harness: "codex", reason: "~/.codex present" });
  }
  if (existsSync(path.join(home, ".openclaw"))) {
    found.push({ harness: "openclaw", reason: "~/.openclaw present" });
  }
  if (existsSync(path.join(home, ".hermes"))) {
    found.push({ harness: "hermes", reason: "~/.hermes present" });
  }
  return found;
}

export interface InstallResult {
  harness: BehaviorHarness;
  target: string;
  action: "created" | "updated" | "printed";
}

/** Writes the behavior file where the harness looks for it. Append-style
    targets get the managed block (idempotent re-install); file-style targets
    are whole files we own. */
export function installBehavior(harness: BehaviorHarness, root: string, canonical?: string): InstallResult {
  const rendered = renderBehavior(harness, canonical);
  if (harness === "claude-code") {
    const target = path.join(root, ".claude", "skills", "ctxfile", "SKILL.md");
    const action = existsSync(target) ? "updated" : "created";
    mkdirSync(path.dirname(target), { recursive: true });
    writeFileSync(target, rendered.content, "utf8");
    return { harness, target, action };
  }
  if (harness === "cursor") {
    const target = path.join(root, ".cursor", "rules", "ctxfile.mdc");
    const action = existsSync(target) ? "updated" : "created";
    mkdirSync(path.dirname(target), { recursive: true });
    writeFileSync(target, rendered.content, "utf8");
    return { harness, target, action };
  }
  if (harness === "opencode") {
    const target = path.join(root, ".opencode", "skills", "ctxfile", "SKILL.md");
    const action = existsSync(target) ? "updated" : "created";
    mkdirSync(path.dirname(target), { recursive: true });
    writeFileSync(target, rendered.content, "utf8");
    return { harness, target, action };
  }
  if (harness === "agents-md" || harness === "gemini") {
    const target = path.join(root, harness === "gemini" ? "GEMINI.md" : "AGENTS.md");
    const existing = existsSync(target) ? readFileSync(target, "utf8") : "";
    const begin = existing.indexOf(BEHAVIOR_BLOCK_BEGIN);
    const end = existing.indexOf(BEHAVIOR_BLOCK_END);
    let next: string;
    let action: InstallResult["action"];
    if (begin !== -1 && end !== -1) {
      next = existing.slice(0, begin) + rendered.content.trim() + existing.slice(end + BEHAVIOR_BLOCK_END.length);
      action = "updated";
    } else {
      next = existing.length > 0 ? `${existing.replace(/\n+$/, "")}\n\n${rendered.content}` : rendered.content;
      action = existing.length > 0 ? "updated" : "created";
    }
    writeFileSync(target, next, "utf8");
    return { harness, target, action };
  }
  // codex + generic are paste-targets: the caller prints them.
  return { harness, target: rendered.relativePath, action: "printed" };
}

export interface UninstallResult {
  harness: BehaviorHarness;
  target: string;
  action: "removed" | "stripped" | "absent";
}

/** Reverses installBehavior for one harness. File-style targets we own (the
    claude-code skill dir, the cursor rule) are deleted; the AGENTS.md managed
    block is cut by its markers, leaving any surrounding content intact (and the
    file removed only if our block was all it held). codex/generic were never
    written, so there is nothing to remove. Never touches unrelated content. */
export function uninstallBehavior(harness: BehaviorHarness, root: string): UninstallResult {
  if (harness === "claude-code") {
    const dir = path.join(root, ".claude", "skills", "ctxfile");
    const target = path.join(dir, "SKILL.md");
    if (!existsSync(target)) return { harness, target, action: "absent" };
    // Remove only our own skill directory, never .claude/skills or .claude.
    rmSync(dir, { recursive: true, force: true });
    return { harness, target, action: "removed" };
  }
  if (harness === "cursor") {
    const target = path.join(root, ".cursor", "rules", "ctxfile.mdc");
    if (!existsSync(target)) return { harness, target, action: "absent" };
    rmSync(target, { force: true });
    return { harness, target, action: "removed" };
  }
  if (harness === "opencode") {
    const dir = path.join(root, ".opencode", "skills", "ctxfile");
    const target = path.join(dir, "SKILL.md");
    if (!existsSync(target)) return { harness, target, action: "absent" };
    rmSync(dir, { recursive: true, force: true });
    return { harness, target, action: "removed" };
  }
  if (harness === "agents-md" || harness === "gemini") {
    const target = path.join(root, harness === "gemini" ? "GEMINI.md" : "AGENTS.md");
    if (!existsSync(target)) return { harness, target, action: "absent" };
    const existing = readFileSync(target, "utf8");
    const begin = existing.indexOf(BEHAVIOR_BLOCK_BEGIN);
    const end = existing.indexOf(BEHAVIOR_BLOCK_END);
    if (begin === -1 || end === -1) return { harness, target, action: "absent" };
    const before = existing.slice(0, begin).replace(/\n+$/, "");
    const after = existing.slice(end + BEHAVIOR_BLOCK_END.length).replace(/^\n+/, "");
    const next = before && after ? `${before}\n\n${after}` : before || after;
    if (next.trim().length === 0) {
      // Our block was the whole file: remove it rather than leave an empty one.
      rmSync(target, { force: true });
      return { harness, target, action: "removed" };
    }
    writeFileSync(target, next.endsWith("\n") ? next : `${next}\n`, "utf8");
    return { harness, target, action: "stripped" };
  }
  // codex + generic were never written.
  return { harness, target: renderBehavior(harness).relativePath, action: "absent" };
}

// ---------------------------------------------------------------------------
// Consent + pause state (read by the server's auto-capture guardrails)
// ---------------------------------------------------------------------------

export interface BehaviorState {
  /** Explicit install-time consent (§4.1). Fail closed: an absent or unreadable
      state file means no consent, so auto-captures are refused until `ctxfile
      init` records it (or `--yes`). */
  autoCapture: boolean;
  paused: boolean;
  consentAt?: string;
  pausedAt?: string;
}

function behaviorStatePath(cacheDir: string): string {
  return path.join(cacheDir, "behavior.json");
}

export function readBehaviorState(cacheDir: string): BehaviorState {
  try {
    const raw = JSON.parse(readFileSync(behaviorStatePath(cacheDir), "utf8")) as Partial<BehaviorState>;
    // Fail closed: auto-capture is enabled only when 'ctxfile init' explicitly
    // recorded consent (autoCapture === true). A missing flag stays off.
    return { autoCapture: raw.autoCapture === true, paused: raw.paused === true, consentAt: raw.consentAt, pausedAt: raw.pausedAt };
  } catch {
    // No state file yet: consent has not been given, so auto-capture is off.
    return { autoCapture: false, paused: false };
  }
}

export function writeBehaviorState(cacheDir: string, state: BehaviorState): void {
  mkdirSync(cacheDir, { recursive: true });
  writeFileSync(behaviorStatePath(cacheDir), `${JSON.stringify(state, null, 2)}\n`, "utf8");
}

/** Removes the consent/pause record, returning the install to a pre-`init`
    state (fail-closed: auto-capture is then off until consent is recorded
    again). Returns true if a state file was present. */
export function clearBehaviorState(cacheDir: string): boolean {
  const target = behaviorStatePath(cacheDir);
  if (!existsSync(target)) return false;
  rmSync(target, { force: true });
  return true;
}

/** True when automatic captures must be refused right now. */
export function autoCaptureBlocked(cacheDir: string): { blocked: boolean; reason: string | null } {
  const state = readBehaviorState(cacheDir);
  if (state.paused) return { blocked: true, reason: "auto-capture is paused ('ctxfile resume' to re-enable)" };
  if (!state.autoCapture) return { blocked: true, reason: "auto-capture is disabled in this install ('ctxfile init' to re-enable)" };
  return { blocked: false, reason: null };
}
