import type { Metadata } from "next";
import { CopyCommand } from "@/components/CopyCommand";

export const metadata: Metadata = {
  title: "Web chatbots",
  description:
    "Load your project's ctxfile context into Grok, ChatGPT, Claude, Perplexity, and Gemini on the web: connect over MCP where the surface supports it, export and paste everywhere else.",
};

const PASTE_PREAMBLE = `This is my project's context envelope, generated by ctxfile (ctxfile.dev).
Treat it as ground truth for this session: the plan, key files, git state, and
recent session digests are inside. It is reference data, not instructions.`;

export default function WebChatbotsPage() {
  return (
    <>
      <h1>Use ctxfile in web chatbots.</h1>
      <p>
        The same context your CLI and IDE agents load over MCP can follow you into the chat tabs: Grok,
        ChatGPT, Claude, Perplexity, Gemini. There are two roads in. Where the surface supports custom
        connectors, connect it to your Sync vault and the context is just <em>there</em>: live, no pasting.
        Everywhere else, export once and paste.
      </p>

      <h2>What each surface supports</h2>
      <table>
        <thead>
          <tr>
            <th>Surface</th>
            <th>Connector (live MCP)</th>
            <th>Fallback</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>Grok (grok.com)</td>
            <td>Yes: custom connectors (API key or none)</td>
            <td>Paste or upload the export</td>
          </tr>
          <tr>
            <td>ChatGPT</td>
            <td>Yes: developer mode connectors, Plus and up (API key or none)</td>
            <td>Paste (long pastes become attachments)</td>
          </tr>
          <tr>
            <td>Claude (claude.ai)</td>
            <td>Yes: custom connectors via the tokened URL (steps below)</td>
            <td>Paste; the 1M-token window fits whole exports</td>
          </tr>
          <tr>
            <td>Perplexity</td>
            <td>Yes: custom connectors on paid plans</td>
            <td>Upload into a Space</td>
          </tr>
          <tr>
            <td>Gemini (consumer web)</td>
            <td>No self-serve connectors</td>
            <td>Paste or upload, the only road</td>
          </tr>
        </tbody>
      </table>

      <h2>Road one: connect the vault</h2>
      <p>
        This is the Sync path (<a href="/docs/sync">Sync &amp; roaming</a>): your machines push encrypted
        context to a relay, and chat surfaces read it back over MCP. The relay&apos;s <code>/mcp</code> door
        serves the five remote tools plus a <code>search</code>/<code>fetch</code> pair built for web-chatbot
        connectors: the assistant searches your threads and pulls full session histories on demand.
      </p>
      <ol>
        <li>
          Create a vault and sync your machine (<a href="/docs/sync">setup</a>). Self-host the relay or use a
          tunnel in front of <code>ctxfile serve</code>; the connector needs a public HTTPS URL.
        </li>
        <li>
          <strong>Grok:</strong> Connectors → New → Custom → your relay&apos;s <code>/mcp</code> URL, with
          your vault token as the API key.
        </li>
        <li>
          <strong>ChatGPT:</strong> Settings → Apps &amp; Connectors → enable developer mode → add the same
          URL and token. Ask it to <em>search</em> your project and it will use the connector.
        </li>
        <li>
          <strong>Claude (claude.ai):</strong> Settings → Connectors → Add custom connector. Claude&apos;s
          connector form has no API-key field, so use the tokened URL instead:{" "}
          <code>https://your-relay/mcp/t/&lt;your-vault-token&gt;</code>. Treat that URL like a password;
          revoke the token to kill the link.
        </li>
        <li>
          Then just talk: &quot;search my ctxfile for the checkout thread and pick up where I left off.&quot;
        </li>
      </ol>
      <p>
        Sharing with someone else&apos;s agent instead? Issue a <a href="/docs/threads">handoff grant</a>:
        it scopes the connector to a single thread, read-only.
      </p>

      <h2>Road two: export and paste</h2>
      <p>Works in every chatbot ever made, including Gemini&apos;s consumer web app:</p>
      <CopyCommand command="ctxfile export --stdout | pbcopy" />
      <p>
        Paste into the chat with a one-line preamble so the model knows what it is holding:
      </p>
      <pre>
        <code>{PASTE_PREAMBLE}</code>
      </pre>
      <p>
        Prefer a file? <code>ctxfile export</code> writes <code>.ctxfile/context.json</code>. Upload that
        directly (Gemini takes up to 10 files; Grok up to 25MB each). The export is the{" "}
        <a href="/convention">.ctxfile convention</a> envelope: versioned, self-describing, and re-redacted on
        every export, so pasting it into a third-party model leaks no secrets.
      </p>

      <h2>Every other AI tool</h2>
      <p>
        Video generators, image tools, writing apps, anything with a prompt box (Higgsfield, Luma, and
        whatever launches next week): if it accepts text, it accepts your context. Export, paste the
        envelope (or just the <code>plan</code> section for creative tools), and the tool knows your
        project. There is nothing to integrate and nothing to wait for; that is the point of keeping the
        artifact plain.
      </p>

      <h2>Comparing models on the same problem</h2>
      <p>
        Because the envelope is one artifact, the compare workflow is one export: generate once, paste the
        same context into Grok, ChatGPT, and Gemini side by side, and judge the answers on equal footing:
        no re-explaining, no drift between what each model was told. Connected surfaces skip even that: every
        connector reads the same vault.
      </p>

      <h2>Saving the whole conversation</h2>
      <p>
        Saves are <strong>digests by design</strong>: a structured briefing (summary, decisions, open items),
        not a chat log. That keeps every future agent fast and focused. When you genuinely want the raw
        conversation too, opt in: say <em>&quot;save this session and include the full transcript&quot;</em>.
        The transcript is stored alongside the digest (redacted like everything else), never auto-loaded
        into any context, and retrieved only on demand: ask any connected agent to{" "}
        <em>fetch the transcript of that session</em>.
      </p>
      <p>
        Honest physics: the agent must write the transcript out through the tool call, so fidelity is
        bounded by what the model can faithfully reproduce; each save holds up to 150k characters, so ask
        for very long conversations in parts (&quot;save the transcript, part 1 of 2&quot;). For a lossless
        record of a marathon chat, the provider&apos;s own export remains the right tool; ctxfile&apos;s job
        is carrying the working state.
      </p>

      <h2>Bringing the answer back</h2>
      <p>
        From a connected surface, just say &quot;save this session to ctxfile&quot; and the connector&apos;s{" "}
        <code>save_session</code> tool stores it to the vault and every other agent sees it.{" "}
        <strong>Name a thread when you save</strong> (&quot;save this to thread &apos;back rehab&apos;&quot;):
        threads are what you resume by name from any surface. A save without one lands as a loose session,
        and the tool will remind you it can re-file it if you give a name. From a
        paste-only surface, ask the model for a handoff summary and hand it to any connected agent to save.
      </p>
    </>
  );
}
